# action.yml
name: 'fetch jwt token'
description: 'fetch jwt token for authentication'
inputs:
  login:  # id of input
    description: 'login name for qbee.io'
    required: true
  password:  # id of input
    description: 'login password for qbee.io'
    required: true
  api_host:  # id of input
    description: 'api host to use'
    required: false
    default: 'www.app.qbee.io'
outputs:
  token:
    description: 'jwt token'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.login }}
    - ${{ inputs.password }}
    - ${{ inputs.api_host }}
